[package]
name = "gluex-rs-py"
version = "0.1.0"
description = "Python bindings for the gluex-rs Rust crate"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "README.md"
keywords = ["gluex", "rcdb", "python"]

[lib]
name = "gluex"
crate-type = ["cdylib"]

[dependencies]
pyo3.workspace = true
