[package]
name = "gluex-rs-py"
version = "0.1.0"
description = "Python bindings for the gluex-rs Rust crate"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "README.md"
keywords = ["gluex", "rcdb", "python"]

[lib]
name = "_gluex"
crate-type = ["cdylib"]

[dependencies]
chrono.workspace = true
gluex-ccdb.workspace = true
gluex-core.workspace = true
gluex-lumi.workspace = true
gluex-rcdb.workspace = true
gluex-rs.workspace = true
pyo3.workspace = true
