[package]
name = "gluex-lumi"
version = "0.4.0"
description = "A Rust crate to calculate luminosity data for the GlueX experiment"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "README.md"
documentation = "https://docs.rs/gluex-lumi"
keywords = ["gluex", "luminosity", "physics", "analysis"]

[lib]
name = "gluex_lumi"
crate-type = ["rlib"]

[dependencies]
chrono.workspace = true
serde.workspace = true
thiserror.workspace = true

gluex-core.workspace = true
gluex-rcdb.workspace = true
gluex-ccdb.workspace = true

[dev-dependencies]
criterion.workspace = true
rusqlite.workspace = true

[lints]
workspace = true
