[package]
name = "gluex-rs"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "gluex"
path = "src/main.rs"

[dependencies]
clap.workspace = true
fastrand.workspace = true
hddm.workspace = true
laddu.workspace = true
serde_json.workspace = true
strum.workspace = true
thiserror.workspace = true

gluex-core.workspace = true
gluex-rcdb.workspace = true
gluex-ccdb.workspace = true
gluex-lumi.workspace = true

[dev-dependencies]
approx.workspace = true
rusqlite.workspace = true

[build-dependencies]
anyhow.workspace = true
hddm.workspace = true
hddm-rs.workspace = true

[lints]
workspace = true
