[package]
name = "gluex-rs"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
fastrand.workspace = true
hddm.workspace = true
laddu.workspace = true
thiserror.workspace = true

gluex-core.workspace = true
gluex-rcdb.workspace = true
gluex-ccdb.workspace = true
gluex-lumi.workspace = true


[build-dependencies]
anyhow.workspace = true
hddm.workspace = true
hddm-rs.workspace = true

[lints]
workspace = true
