#[derive(Copy, Clone, Debug, Eq, Hash, PartialEq)]
pub enum Charge {
    Charged,
    Positive,
    Negative,
    Neutral,
    AllCharges,
}

use std::{fmt, str::FromStr};

use strum::VariantArray;

#[derive(Copy, Clone, Debug, Eq, Hash, PartialEq, Default, VariantArray)]
pub enum Particle {
    #[default]
    UnknownParticle,
    Gamma,
    Positron,
    Electron,
    Neutrino,
    MuonPlus,
    MuonMinus,
    Pi0,
    PiPlus,
    PiMinus,
    KLong,
    KPlus,
    KMinus,
    Neutron,
    Proton,
    AntiProton,
    KShort,
    Eta,
    Lambda,
    SigmaPlus,
    Sigma0,
    SigmaMinus,
    Xi0,
    XiMinus,
    OmegaMinus,
    AntiNeutron,
    AntiLambda,
    AntiSigmaMinus,
    AntiSigma0,
    AntiSigmaPlus,
    AntiXi0,
    AntiXiPlus,
    AntiOmegaPlus,
    Deuteron,
    Triton,
    Helium,
    Geantino,
    He3,
    GammaOptical,
    Li6,
    Li7,
    Be7,
    Be9,
    B10,
    B11,
    C12,
    N14,
    O16,
    F19,
    Ne20,
    Na23,
    Mg24,
    Al27,
    Si28,
    P31,
    S32,
    Cl35,
    Ar36,
    K39,
    Ca40,
    Sc45,
    Ti48,
    V51,
    Cr52,
    Mn55,
    Fe56,
    Co59,
    Ni58,
    Cu63,
    Zn64,
    Ge74,
    Se80,
    Kr84,
    Sr88,
    Zr90,
    Mo98,
    Pd106,
    Cd114,
    Sn120,
    Xe132,
    Ba138,
    Ce140,
    Sm152,
    Dy164,
    Yb174,
    W184,
    Pt194,
    Au197,
    Hg202,
    Pb208,
    U238,
    Ta181,
    Rho0,
    RhoPlus,
    RhoMinus,
    Omega,
    Phi,
    EtaPrime,
    A0_980,
    F0_980,
    KStar892Zero,
    KStar892Plus,
    KStar892Minus,
    AntiKStar892Zero,
    K1Plus1400,
    K1Minus1400,
    B1Plus1235,
    Sigma1385Minus,
    Sigma1385Zero,
    Sigma1385Plus,
    Jpsi,
    EtaC,
    ChiC0,
    ChiC1,
    ChiC2,
    Psi2s,
    D0,
    DPlus,
    DStar0,
    DStarPlus,
    LambdaC,
    AntiD0,
    DMinus,
    DStarMinus,
    SigmaCPlusPlus,
    DeltaPlusPlus,
}

impl Particle {
    pub fn is_unknown(&self) -> bool {
        matches!(self, Self::UnknownParticle)
    }

    pub fn to_geant3(&self) -> usize {
        match self {
            Self::UnknownParticle => 0,
            Self::Gamma => 1,
            Self::Positron => 2,
            Self::Electron => 3,
            Self::Neutrino => 4,
            Self::MuonPlus => 5,
            Self::MuonMinus => 6,
            Self::Pi0 => 7,
            Self::PiPlus => 8,
            Self::PiMinus => 9,
            Self::KLong => 10,
            Self::KPlus => 11,
            Self::KMinus => 12,
            Self::Neutron => 13,
            Self::Proton => 14,
            Self::AntiProton => 15,
            Self::KShort => 16,
            Self::Eta => 17,
            Self::Lambda => 18,
            Self::SigmaPlus => 19,
            Self::Sigma0 => 20,
            Self::SigmaMinus => 21,
            Self::Xi0 => 22,
            Self::XiMinus => 23,
            Self::OmegaMinus => 24,
            Self::AntiNeutron => 25,
            Self::AntiLambda => 26,
            Self::AntiSigmaMinus => 27,
            Self::AntiSigma0 => 28,
            Self::AntiSigmaPlus => 29,
            Self::AntiXi0 => 30,
            Self::AntiXiPlus => 31,
            Self::AntiOmegaPlus => 32,
            Self::Deuteron => 45,
            Self::Triton => 46,
            Self::Helium => 47,
            Self::Geantino => 48,
            Self::He3 => 49,
            Self::GammaOptical => 50,
            Self::Li6 => 61,
            Self::Li7 => 62,
            Self::Be7 => 63,
            Self::Be9 => 64,
            Self::B10 => 65,
            Self::B11 => 66,
            Self::C12 => 67,
            Self::N14 => 68,
            Self::O16 => 69,
            Self::F19 => 70,
            Self::Ne20 => 71,
            Self::Na23 => 72,
            Self::Mg24 => 73,
            Self::Al27 => 74,
            Self::Si28 => 75,
            Self::P31 => 76,
            Self::S32 => 77,
            Self::Cl35 => 78,
            Self::Ar36 => 79,
            Self::K39 => 80,
            Self::Ca40 => 81,
            Self::Sc45 => 82,
            Self::Ti48 => 83,
            Self::V51 => 84,
            Self::Cr52 => 85,
            Self::Mn55 => 86,
            Self::Fe56 => 87,
            Self::Co59 => 88,
            Self::Ni58 => 89,
            Self::Cu63 => 90,
            Self::Zn64 => 91,
            Self::Ge74 => 92,
            Self::Se80 => 93,
            Self::Kr84 => 94,
            Self::Sr88 => 95,
            Self::Zr90 => 96,
            Self::Mo98 => 97,
            Self::Pd106 => 98,
            Self::Cd114 => 99,
            Self::Sn120 => 100,
            Self::Xe132 => 101,
            Self::Ba138 => 102,
            Self::Ce140 => 103,
            Self::Sm152 => 104,
            Self::Dy164 => 105,
            Self::Yb174 => 106,
            Self::W184 => 107,
            Self::Pt194 => 108,
            Self::Au197 => 109,
            Self::Hg202 => 110,
            Self::Pb208 => 111,
            Self::U238 => 112,
            Self::Ta181 => 113,
            Self::Rho0 => 44,     // was 157
            Self::RhoPlus => 42,  // was 158
            Self::RhoMinus => 43, // was 159
            Self::Omega => 33,    // was 160
            Self::Phi => 34,      // was 162
            Self::EtaPrime => 35, // was 161
            Self::A0_980 => 163,
            Self::F0_980 => 164,
            Self::KStar892Zero => 165,
            Self::KStar892Plus => 166,
            Self::KStar892Minus => 167,
            Self::AntiKStar892Zero => 168,
            Self::K1Plus1400 => 169,
            Self::K1Minus1400 => 170,
            Self::B1Plus1235 => 171,
            Self::Sigma1385Minus => 172,
            Self::Sigma1385Zero => 173,
            Self::Sigma1385Plus => 174,
            Self::Jpsi => 183,
            Self::EtaC => 184,
            Self::ChiC0 => 185,
            Self::ChiC1 => 186,
            Self::ChiC2 => 187,
            Self::Psi2s => 188,
            Self::D0 => 189,
            Self::DPlus => 190,
            Self::DStar0 => 191,
            Self::DStarPlus => 192,
            Self::LambdaC => 193,
            Self::AntiD0 => 194,
            Self::DMinus => 195,
            Self::DStarMinus => 196,
            Self::SigmaCPlusPlus => 197,
            Self::DeltaPlusPlus => 182,
        }
    }
    pub fn is_lepton(&self) -> bool {
        matches!(
            self,
            Self::Electron | Self::Positron | Self::MuonPlus | Self::MuonMinus | Self::Neutrino
        )
    }

    pub fn to_particle_type(&self) -> &str {
        match self {
            Self::UnknownParticle => "Unknown",
            Self::Gamma => "Gamma",
            Self::Positron => "Positron",
            Self::Electron => "Electron",
            Self::Neutrino => "Neutrino",
            Self::MuonPlus => "Muon+",
            Self::MuonMinus => "Muon-",
            Self::Pi0 => "Pi0",
            Self::PiPlus => "Pi+",
            Self::PiMinus => "Pi-",
            Self::KLong => "KLong",
            Self::KPlus => "K+",
            Self::KMinus => "K-",
            Self::Neutron => "Neutron",
            Self::Proton => "Proton",
            Self::AntiProton => "AntiProton",
            Self::KShort => "KShort",
            Self::Eta => "Eta",
            Self::Lambda => "Lambda",
            Self::SigmaPlus => "Sigma+",
            Self::Sigma0 => "Sigma0",
            Self::SigmaMinus => "Sigma-",
            Self::Xi0 => "Xi0",
            Self::XiMinus => "Xi-",
            Self::OmegaMinus => "Omega-",
            Self::AntiNeutron => "AntiNeutron",
            Self::AntiLambda => "AntiLambda",
            Self::AntiSigmaMinus => "AntiSigma-",
            Self::AntiSigma0 => "AntiSigma0",
            Self::AntiSigmaPlus => "AntiSigma+",
            Self::AntiXi0 => "AntiXi0",
            Self::AntiXiPlus => "AntiXi+",
            Self::AntiOmegaPlus => "AntiOmega+",
            Self::Deuteron => "Deuteron",
            Self::Triton => "Triton",
            Self::Helium => "Helium",
            Self::Geantino => "Geantino",
            Self::He3 => "Helium-3",
            Self::GammaOptical => "GammaOptical",
            Self::Li6 => "Lithium-6",
            Self::Li7 => "Lithium-7",
            Self::Be7 => "Beryllium-7",
            Self::Be9 => "Beryllium-9",
            Self::B10 => "Boron-10",
            Self::B11 => "Boron-11",
            Self::C12 => "Carbon-12",
            Self::N14 => "Nitrogen",
            Self::O16 => "Oxygen",
            Self::F19 => "Flourine",
            Self::Ne20 => "Neon",
            Self::Na23 => "Sodium",
            Self::Mg24 => "Magnesium",
            Self::Al27 => "Aluminum",
            Self::Si28 => "Silicon",
            Self::P31 => "Phosphorous",
            Self::S32 => "Sulphur",
            Self::Cl35 => "Chlorine",
            Self::Ar36 => "Argon",
            Self::K39 => "Potassium",
            Self::Ca40 => "Calcium",
            Self::Sc45 => "Scandium",
            Self::Ti48 => "Titanium",
            Self::V51 => "Vanadium",
            Self::Cr52 => "Chromium",
            Self::Mn55 => "Manganese",
            Self::Fe56 => "Iron",
            Self::Co59 => "Cobalt",
            Self::Ni58 => "Nickel",
            Self::Cu63 => "Copper",
            Self::Zn64 => "Zinc",
            Self::Ge74 => "Germanium",
            Self::Se80 => "Selenium",
            Self::Kr84 => "Krypton",
            Self::Sr88 => "Strontium",
            Self::Zr90 => "Zirconium",
            Self::Mo98 => "Molybdenum",
            Self::Pd106 => "Palladium",
            Self::Cd114 => "Cadmium",
            Self::Sn120 => "Tin",
            Self::Xe132 => "Xenon",
            Self::Ba138 => "Barium",
            Self::Ce140 => "Cesium",
            Self::Sm152 => "Samerium",
            Self::Dy164 => "Dysprosium",
            Self::Yb174 => "Ytterbium",
            Self::W184 => "Tungsten",
            Self::Pt194 => "Platinum",
            Self::Au197 => "Gold",
            Self::Hg202 => "Mercury",
            Self::Pb208 => "Lead",
            Self::U238 => "Uranium",
            Self::Ta181 => "Tantalum",
            Self::Rho0 => "Rho0",
            Self::RhoPlus => "Rho+",
            Self::RhoMinus => "Rho-",
            Self::Omega => "Omega",
            Self::Phi => "Phi",
            Self::EtaPrime => "EtaPrime",
            Self::A0_980 => "a0(980)",
            Self::F0_980 => "f0(980)",
            Self::KStar892Zero => "K*(892)0",
            Self::KStar892Plus => "K*(892)+",
            Self::KStar892Minus => "K*(892)-",
            Self::AntiKStar892Zero => "antiK*(892)0",
            Self::K1Plus1400 => "K1(1440)+",
            Self::K1Minus1400 => "K1(1440)-",
            Self::B1Plus1235 => "b1(1235)+",
            Self::Sigma1385Minus => "Sigma(1385)-",
            Self::Sigma1385Zero => "Sigma(1385)0",
            Self::Sigma1385Plus => "Sigma(1385)+",
            Self::Jpsi => "Jpsi",
            Self::EtaC => "EtaC",
            Self::ChiC0 => "ChiC0",
            Self::ChiC1 => "ChiC1",
            Self::ChiC2 => "ChiC2",
            Self::Psi2s => "Psi(2S)",
            Self::D0 => "D0",
            Self::DPlus => "D+",
            Self::DStar0 => "D*0",
            Self::DStarPlus => "D*+",
            Self::LambdaC => "LambdaC",
            Self::AntiD0 => "AntiD0",
            Self::DMinus => "D-",
            Self::DStarMinus => "D*-",
            Self::SigmaCPlusPlus => "SigmaC++",
            Self::DeltaPlusPlus => "Delta++",
        }
    }

    fn enum_name(&self) -> &str {
        match self {
            Self::UnknownParticle => "Unknown",
            Self::Gamma => "Photon",
            Self::Positron => "Positron",
            Self::Electron => "Electron",
            Self::Neutrino => "Neutrino",
            Self::MuonPlus => "MuonPlus",
            Self::MuonMinus => "MuonMinus",
            Self::Pi0 => "Pi0",
            Self::PiPlus => "PiPlus",
            Self::PiMinus => "PiMinus",
            Self::KLong => "KLong",
            Self::KPlus => "KPlus",
            Self::KMinus => "KMinus",
            Self::Neutron => "Neutron",
            Self::Proton => "Proton",
            Self::AntiProton => "AntiProton",
            Self::KShort => "KShort",
            Self::Eta => "Eta",
            Self::Lambda => "Lambda",
            Self::SigmaPlus => "SigmaPlus",
            Self::Sigma0 => "Sigma0",
            Self::SigmaMinus => "SigmaMinus",
            Self::Xi0 => "Xi0",
            Self::XiMinus => "XiMinus",
            Self::OmegaMinus => "OmegaMinus",
            Self::AntiNeutron => "AntiNeutron",
            Self::AntiLambda => "AntiLambda",
            Self::AntiSigmaMinus => "AntiSigmaMinus",
            Self::AntiSigma0 => "AntiSigma0",
            Self::AntiSigmaPlus => "AntiSigmaPlus",
            Self::AntiXi0 => "AntiXi0",
            Self::AntiXiPlus => "AntiXiPlus",
            Self::AntiOmegaPlus => "AntiOmegaPlus",
            Self::Deuteron => "Deuteron",
            Self::Triton => "Triton",
            Self::Helium => "Helium",
            Self::Geantino => "Geantino",
            Self::He3 => "Helium-3",
            Self::GammaOptical => "GammaOptical",
            Self::Li6 => "Lithium-6",
            Self::Li7 => "Lithium-7",
            Self::Be7 => "Beryllium-7",
            Self::Be9 => "Beryllium-9",
            Self::B10 => "Boron-10",
            Self::B11 => "Boron-11",
            Self::C12 => "Carbon-12",
            Self::N14 => "Nitrogen",
            Self::O16 => "Oxygen",
            Self::F19 => "Flourine",
            Self::Ne20 => "Neon",
            Self::Na23 => "Sodium",
            Self::Mg24 => "Magnesium",
            Self::Al27 => "Aluminum",
            Self::Si28 => "Silicon",
            Self::P31 => "Phosphorous",
            Self::S32 => "Sulphur",
            Self::Cl35 => "Chlorine",
            Self::Ar36 => "Argon",
            Self::K39 => "Potassium",
            Self::Ca40 => "Calcium",
            Self::Sc45 => "Scandium",
            Self::Ti48 => "Titanium",
            Self::V51 => "Vanadium",
            Self::Cr52 => "Chromium",
            Self::Mn55 => "Manganese",
            Self::Fe56 => "Iron",
            Self::Co59 => "Cobalt",
            Self::Ni58 => "Nickel",
            Self::Cu63 => "Copper",
            Self::Zn64 => "Zinc",
            Self::Ge74 => "Germanium",
            Self::Se80 => "Selenium",
            Self::Kr84 => "Krypton",
            Self::Sr88 => "Strontium",
            Self::Zr90 => "Zirconium",
            Self::Mo98 => "Molybdenum",
            Self::Pd106 => "Palladium",
            Self::Cd114 => "Cadmium",
            Self::Sn120 => "Tin",
            Self::Xe132 => "Xenon",
            Self::Ba138 => "Barium",
            Self::Ce140 => "Cesium",
            Self::Sm152 => "Samerium",
            Self::Dy164 => "Dysprosium",
            Self::Yb174 => "Ytterbium",
            Self::W184 => "Tungsten",
            Self::Pt194 => "Platinum",
            Self::Au197 => "Gold",
            Self::Hg202 => "Mercury",
            Self::Pb208 => "Lead",
            Self::U238 => "Uranium",
            Self::Ta181 => "Tantalum",
            Self::Rho0 => "Rho0",
            Self::RhoPlus => "RhoPlus",
            Self::RhoMinus => "RhoMinus",
            Self::Omega => "omega",
            Self::Phi => "phiMeson",
            Self::EtaPrime => "EtaPrime",
            Self::A0_980 => "a0_980",
            Self::F0_980 => "f0_980",
            Self::KStar892Zero => "KStar_892_0",
            Self::KStar892Plus => "KStar_892_Plus",
            Self::KStar892Minus => "KStar_892_Minus",
            Self::AntiKStar892Zero => "AntiKStar_892_0",
            Self::K1Plus1400 => "K1_1400_Plus",
            Self::K1Minus1400 => "K1_1400_Minus",
            Self::B1Plus1235 => "b1_1235_Plus",
            Self::Sigma1385Minus => "Sigma_1385_Minus",
            Self::Sigma1385Zero => "Sigma_1385_0",
            Self::Sigma1385Plus => "Sigma_1385_Plus",
            Self::Jpsi => "Jpsi",
            Self::EtaC => "Eta_c",
            Self::ChiC0 => "Chi_c0",
            Self::ChiC1 => "Chi_c1",
            Self::ChiC2 => "Chi_c2",
            Self::Psi2s => "Psi2s",
            Self::D0 => "D0",
            Self::DPlus => "DPlus",
            Self::DStar0 => "Dstar0",
            Self::DStarPlus => "DstarPlus",
            Self::LambdaC => "Lambda_c",
            Self::AntiD0 => "AntiD0",
            Self::DMinus => "DMinus",
            Self::DStarMinus => "DstarMinus",
            Self::SigmaCPlusPlus => "Sigma_cPlusPlus",
            Self::DeltaPlusPlus => "DeltaPlusPlus",
        }
    }

    pub fn to_evtgen(&self) -> &str {
        match self {
            Self::UnknownParticle => "Unknown",
            Self::Gamma => "gamma",
            Self::Positron => "e+",
            Self::Electron => "e-",
            Self::Neutrino => "nu_e",
            Self::MuonPlus => "mu+",
            Self::MuonMinus => "mu-",
            Self::Pi0 => "pi0",
            Self::PiPlus => "pi+",
            Self::PiMinus => "pi-",
            Self::KLong => "K_L0",
            Self::KPlus => "K+",
            Self::KMinus => "K-",
            Self::Neutron => "n0",
            Self::Proton => "p+",
            Self::AntiProton => "anti-p-",
            Self::KShort => "K_S0",
            Self::Eta => "eta",
            Self::Lambda => "Lambda0",
            Self::SigmaPlus => "Sigma+",
            Self::Sigma0 => "Sigma0",
            Self::SigmaMinus => "Sigma-",
            Self::Xi0 => "Xi0",
            Self::XiMinus => "Xi-",
            Self::OmegaMinus => "Omega-",
            Self::AntiNeutron => "anti-n0",
            Self::AntiLambda => "anti-Lambda0",
            Self::AntiSigmaMinus => "anti-Sigma-",
            Self::AntiSigma0 => "anti-Sigma0",
            Self::AntiSigmaPlus => "anti-Sigma+",
            Self::AntiXi0 => "anti-Xi0",
            Self::AntiXiPlus => "anti-Xi+",
            Self::AntiOmegaPlus => "anti-Omega+",
            Self::Deuteron => "deuteron",
            Self::Triton => "Triton", // FIX: see particleType.h
            Self::Helium => "Helium", // FIX: see particleType.h
            Self::Geantino => "geantino",
            Self::He3 => "He3",
            Self::GammaOptical => "gammaOptical",
            Self::Li6 => "Lithium-6",
            Self::Li7 => "Lithium-7",
            Self::Be7 => "Beryllium-7",
            Self::Be9 => "Beryllium-9",
            Self::B10 => "Boron-10",
            Self::B11 => "Boron-11",
            Self::C12 => "Carbon-12",
            Self::N14 => "Nitrogen",
            Self::O16 => "Oxygen",
            Self::F19 => "Flourine",
            Self::Ne20 => "Neon",
            Self::Na23 => "Sodium",
            Self::Mg24 => "Magnesium",
            Self::Al27 => "Aluminum",
            Self::Si28 => "Silicon",
            Self::P31 => "Phosphorous",
            Self::S32 => "Sulphur",
            Self::Cl35 => "Chlorine",
            Self::Ar36 => "Argon",
            Self::K39 => "Potassium",
            Self::Ca40 => "Calcium",
            Self::Sc45 => "Scandium",
            Self::Ti48 => "Titanium",
            Self::V51 => "Vanadium",
            Self::Cr52 => "Chromium",
            Self::Mn55 => "Manganese",
            Self::Fe56 => "Iron",
            Self::Co59 => "Cobalt",
            Self::Ni58 => "Nickel",
            Self::Cu63 => "Copper",
            Self::Zn64 => "Zinc",
            Self::Ge74 => "Germanium",
            Self::Se80 => "Selenium",
            Self::Kr84 => "Krypton",
            Self::Sr88 => "Strontium",
            Self::Zr90 => "Zirconium",
            Self::Mo98 => "Molybdenum",
            Self::Pd106 => "Palladium",
            Self::Cd114 => "Cadmium",
            Self::Sn120 => "Tin",
            Self::Xe132 => "Xenon",
            Self::Ba138 => "Barium",
            Self::Ce140 => "Cesium",
            Self::Sm152 => "Samerium",
            Self::Dy164 => "Dysprosium",
            Self::Yb174 => "Ytterbium",
            Self::W184 => "Tungsten",
            Self::Pt194 => "Platinum",
            Self::Au197 => "Gold",
            Self::Hg202 => "Mercury",
            Self::Pb208 => "Lead",
            Self::U238 => "Uranium",
            Self::Ta181 => "Tantalum",
            Self::Rho0 => "rho0",
            Self::RhoPlus => "rho+",
            Self::RhoMinus => "rho-",
            Self::Omega => "omega",
            Self::Phi => "phi",
            Self::EtaPrime => "eta'",
            Self::A0_980 => "a_0",
            Self::F0_980 => "f_0",
            Self::KStar892Zero => "K*0",
            Self::KStar892Plus => "K*+",
            Self::KStar892Minus => "K*-",
            Self::AntiKStar892Zero => "anti-K*0",
            Self::K1Plus1400 => "K'_1+",
            Self::K1Minus1400 => "K'_1-",
            Self::B1Plus1235 => "b_1+",
            Self::Sigma1385Minus => "Sigma_1385_Minus",
            Self::Sigma1385Zero => "Sigma_1385_0",
            Self::Sigma1385Plus => "Sigma_1385_Plus",
            Self::Jpsi => "J/psi",
            Self::EtaC => "eta_c",
            Self::ChiC0 => "chi_c0",
            Self::ChiC1 => "chi_c1",
            Self::ChiC2 => "chi_c2",
            Self::Psi2s => "psi(2S)",
            Self::D0 => "D0",
            Self::DPlus => "D+",
            Self::DStar0 => "D*0",
            Self::DStarPlus => "D*+",
            Self::LambdaC => "Lambda_c0",
            Self::AntiD0 => "anti-D0",
            Self::DMinus => "D-",
            Self::DStarMinus => "D*-",
            Self::SigmaCPlusPlus => "Sigma_c++",
            Self::DeltaPlusPlus => "Delta++",
        }
    }

    pub fn short_name(&self) -> &str {
        match self {
            Self::UnknownParticle => "x",
            Self::Gamma => "g",
            Self::Positron => "ep",
            Self::Electron => "em",
            Self::Neutrino => "nu",
            Self::MuonPlus => "mup",
            Self::MuonMinus => "mum",
            Self::Pi0 => "pi0",
            Self::PiPlus => "pip",
            Self::PiMinus => "pim",
            Self::KLong => "kl",
            Self::KPlus => "kp",
            Self::KMinus => "km",
            Self::Neutron => "n",
            Self::Proton => "prot",
            Self::AntiProton => "antip",
            Self::KShort => "ks",
            Self::Eta => "eta",
            Self::Lambda => "lamb",
            Self::SigmaPlus => "sigp",
            Self::Sigma0 => "sig0",
            Self::SigmaMinus => "sigm",
            Self::Xi0 => "xi0",
            Self::XiMinus => "xim",
            Self::OmegaMinus => "omegam",
            Self::AntiNeutron => "antin",
            Self::AntiLambda => "antilamb",
            Self::AntiSigmaMinus => "antisigm",
            Self::AntiSigma0 => "antisig0",
            Self::AntiSigmaPlus => "antisigp",
            Self::AntiXi0 => "antixi0",
            Self::AntiXiPlus => "antixip",
            Self::AntiOmegaPlus => "antiomegap",
            Self::Deuteron => "d",
            Self::Triton => "tri",
            Self::Helium => "he",
            Self::Geantino => "geant",
            Self::He3 => "he3",
            Self::GammaOptical => "gammaoptical",
            Self::Li6 => "li6",
            Self::Li7 => "li7",
            Self::Be7 => "be7",
            Self::Be9 => "be9",
            Self::B10 => "b10",
            Self::B11 => "b11",
            Self::C12 => "c12",
            Self::N14 => "n14",
            Self::O16 => "o16",
            Self::F19 => "f19",
            Self::Ne20 => "ne20",
            Self::Na23 => "na23",
            Self::Mg24 => "mg24",
            Self::Al27 => "al27",
            Self::Si28 => "si28",
            Self::P31 => "p31",
            Self::S32 => "s32",
            Self::Cl35 => "cl35",
            Self::Ar36 => "ar36",
            Self::K39 => "k39",
            Self::Ca40 => "ca40",
            Self::Sc45 => "sc45",
            Self::Ti48 => "ti48",
            Self::V51 => "v51",
            Self::Cr52 => "cr52",
            Self::Mn55 => "mn55",
            Self::Fe56 => "fe56",
            Self::Co59 => "co59",
            Self::Ni58 => "ni58",
            Self::Cu63 => "cu63",
            Self::Zn64 => "zn64",
            Self::Ge74 => "ge74",
            Self::Se80 => "se80",
            Self::Kr84 => "kr84",
            Self::Sr88 => "sr88",
            Self::Zr90 => "zr90",
            Self::Mo98 => "mo98",
            Self::Pd106 => "pd106",
            Self::Cd114 => "cd114",
            Self::Sn120 => "sn120",
            Self::Xe132 => "xe132",
            Self::Ba138 => "ba138",
            Self::Ce140 => "ce140",
            Self::Sm152 => "sm152",
            Self::Dy164 => "dy164",
            Self::Yb174 => "yb174",
            Self::W184 => "w184",
            Self::Pt194 => "pt194",
            Self::Au197 => "au197",
            Self::Hg202 => "hg202",
            Self::Pb208 => "pb208",
            Self::U238 => "u238",
            Self::Ta181 => "ta181",
            Self::Rho0 => "Rho0",
            Self::RhoPlus => "RhoPlus",
            Self::RhoMinus => "RhoMinus",
            Self::Omega => "omega",
            Self::Phi => "phi",
            Self::EtaPrime => "etapr",
            Self::A0_980 => "a0_980",
            Self::F0_980 => "f0_980",
            Self::KStar892Zero => "KStar_892_0",
            Self::KStar892Plus => "KStar_892_Plus",
            Self::KStar892Minus => "KStar_892_Minus",
            Self::AntiKStar892Zero => "AntiKStar_892_0",
            Self::K1Plus1400 => "K1_1400_Plus",
            Self::K1Minus1400 => "K1_1400_Minus",
            Self::B1Plus1235 => "b1_1235_Plus",
            Self::Sigma1385Minus => "Sigma_1385_Minus",
            Self::Sigma1385Zero => "Sigma_1385_0",
            Self::Sigma1385Plus => "Sigma_1385_Plus",
            Self::Jpsi => "jpsi",
            Self::EtaC => "etac",
            Self::ChiC0 => "chic0",
            Self::ChiC1 => "chic1",
            Self::ChiC2 => "chic2",
            Self::Psi2s => "psi2s",
            Self::D0 => "d0",
            Self::DPlus => "dp",
            Self::DStar0 => "ds0",
            Self::DStarPlus => "dsp",
            Self::LambdaC => "lambc",
            Self::AntiD0 => "antid0",
            Self::DMinus => "dm",
            Self::DStarMinus => "dsm",
            Self::SigmaCPlusPlus => "sigcpp",
            Self::DeltaPlusPlus => "DeltaPlusPlus",
        }
    }

    pub fn from_particle_type(particle_name: &str) -> Self {
        match particle_name {
            "Gamma" | "Photon" => Self::Gamma,
            "Positron" => Self::Positron,
            "Electron" => Self::Electron,
            "Neutrino" => Self::Neutrino,
            "Muon+" => Self::MuonPlus,
            "Muon-" => Self::MuonMinus,
            "Pi0" => Self::Pi0,
            "Pi+" => Self::PiPlus,
            "Pi-" => Self::PiMinus,
            "KLong" => Self::KLong,
            "K+" => Self::KPlus,
            "K-" => Self::KMinus,
            "Neutron" => Self::Neutron,
            "Proton" => Self::Proton,
            "AntiProton" => Self::AntiProton,
            "KShort" => Self::KShort,
            "Eta" => Self::Eta,
            "Lambda" => Self::Lambda,
            "Sigma+" => Self::SigmaPlus,
            "Sigma0" => Self::Sigma0,
            "Sigma-" => Self::SigmaMinus,
            "Xi0" => Self::Xi0,
            "Xi-" => Self::XiMinus,
            "Omega-" => Self::OmegaMinus,
            "AntiNeutron" => Self::AntiNeutron,
            "AntiLambda" => Self::AntiLambda,
            "AntiSigma-" => Self::AntiSigmaMinus,
            "AntiSigma0" => Self::AntiSigma0,
            "AntiSigma+" => Self::AntiSigmaPlus,
            "AntiXi0" => Self::AntiXi0,
            "AntiXi+" => Self::AntiXiPlus,
            "AntiOmega+" => Self::AntiOmegaPlus,
            "Deuteron" => Self::Deuteron,
            "Triton" => Self::Triton,
            "Helium" => Self::Helium,
            "Geantino" => Self::Geantino,
            "Helium-3" => Self::He3,
            "GammaOptical" => Self::GammaOptical,
            "Lithium-6" => Self::Li6,
            "Lithium-7" => Self::Li7,
            "Beryllium-7" => Self::Be7,
            "Beryllium-9" => Self::Be9,
            "Boron-10" => Self::B10,
            "Boron-11" => Self::B11,
            "Carbon" | "Carbon-12" => Self::C12,
            "Nitrogen" => Self::N14,
            "Oxygen" => Self::O16,
            "Flourine" => Self::F19,
            "Neon" => Self::Ne20,
            "Sodium" => Self::Na23,
            "Magnesium" => Self::Mg24,
            "Aluminum" => Self::Al27,
            "Silicon" => Self::Si28,
            "Phosphorous" => Self::P31,
            "Sulfur" | "Sulphur" => Self::S32,
            "Chlorine" => Self::Cl35,
            "Argon" => Self::Ar36,
            "Potassium" => Self::K39,
            "Calcium" => Self::Ca40,
            "Scandium" => Self::Sc45,
            "Titanium" => Self::Ti48,
            "Vanadium" => Self::V51,
            "Chromium" => Self::Cr52,
            "Manganese" => Self::Mn55,
            "Iron" => Self::Fe56,
            "Cobalt" => Self::Co59,
            "Nickel" => Self::Ni58,
            "Copper" => Self::Cu63,
            "Zinc" => Self::Zn64,
            "Germanium" => Self::Ge74,
            "Selenium" => Self::Se80,
            "Krypton" => Self::Kr84,
            "Strontium" => Self::Sr88,
            "Zirconium" => Self::Zr90,
            "Molybdenum" => Self::Mo98,
            "Palladium" => Self::Pd106,
            "Cadmium" => Self::Cd114,
            "Tin" => Self::Sn120,
            "Xenon" => Self::Xe132,
            "Barium" => Self::Ba138,
            "Cesium" => Self::Ce140,
            "Samerium" => Self::Sm152,
            "Dysprosium" => Self::Dy164,
            "Ytterbium" => Self::Yb174,
            "Tungsten" => Self::W184,
            "Platinum" => Self::Pt194,
            "Gold" => Self::Au197,
            "Mercury" => Self::Hg202,
            "Lead" => Self::Pb208,
            "Uranium" => Self::U238,
            "Tantalum" => Self::Ta181,
            "Rho0" => Self::Rho0,
            "Rho+" => Self::RhoPlus,
            "Rho-" => Self::RhoMinus,
            "Omega" => Self::Omega,
            "EtaPrime" => Self::EtaPrime,
            "Phi" => Self::Phi,
            "a0(980)" => Self::A0_980,
            "f0(980)" => Self::F0_980,
            "K*(892)0" => Self::KStar892Zero,
            "K*(892)+" => Self::KStar892Plus,
            "K*(892)-" => Self::KStar892Minus,
            "antiK*(892)0" => Self::AntiKStar892Zero,
            "K1(1400)+" | "K1(1440)+" => Self::K1Plus1400,
            "K1(1400)-" | "K1(1440)-" => Self::K1Minus1400,
            "b1(1235)+" => Self::B1Plus1235,
            "Sigma(1385)+" => Self::Sigma1385Plus,
            "Sigma(1385)0" => Self::Sigma1385Zero,
            "Sigma(1385)-" => Self::Sigma1385Minus,
            "Jpsi" => Self::Jpsi,
            "EtaC" => Self::EtaC,
            "ChiC0" => Self::ChiC0,
            "ChiC1" => Self::ChiC1,
            "ChiC2" => Self::ChiC2,
            "Psi(2S)" => Self::Psi2s,
            "D0" => Self::D0,
            "AntiD0" => Self::AntiD0,
            "D+" => Self::DPlus,
            "D-" => Self::DMinus,
            "D*0" => Self::DStar0,
            "D*+" => Self::DStarPlus,
            "D*-" => Self::DStarMinus,
            "LambdaC" => Self::LambdaC,
            "SigmaC++" => Self::SigmaCPlusPlus,
            "Delta++" => Self::DeltaPlusPlus,
            _ => Self::UnknownParticle,
        }
    }

    pub fn is_fixed_mass(&self) -> bool {
        !matches!(
            self,
            Self::Rho0
                | Self::RhoPlus
                | Self::RhoMinus
                | Self::Omega
                | Self::Phi
                | Self::EtaPrime
                | Self::A0_980
                | Self::F0_980
                | Self::KStar892Zero
                | Self::KStar892Plus
                | Self::KStar892Minus
                | Self::AntiKStar892Zero
                | Self::K1Plus1400
                | Self::K1Minus1400
                | Self::B1Plus1235
                | Self::Sigma1385Minus
                | Self::Sigma1385Zero
                | Self::Sigma1385Plus
                | Self::EtaC
                | Self::ChiC0
                | Self::DeltaPlusPlus
        )
    }

    pub fn is_resonance(&self) -> bool {
        if self.is_fixed_mass() {
            return false;
        }
        !matches!(self, Self::UnknownParticle | Self::Phi | Self::Omega)
    }

    pub fn is_detached_vertex(&self) -> bool {
        matches!(
            self,
            Self::MuonPlus
                | Self::MuonMinus
                | Self::PiPlus
                | Self::PiMinus
                | Self::KShort
                | Self::KLong
                | Self::KPlus
                | Self::KMinus
                | Self::Neutron
                | Self::Lambda
                | Self::SigmaPlus
                | Self::SigmaMinus
                | Self::Xi0
                | Self::XiMinus
                | Self::OmegaMinus
                | Self::AntiNeutron
                | Self::AntiLambda
                | Self::AntiSigmaMinus
                | Self::AntiSigmaPlus
                | Self::AntiXi0
                | Self::AntiXiPlus
                | Self::AntiOmegaPlus
                | Self::Deuteron
                | Self::Triton
                | Self::Helium
                | Self::He3
        )
    }

    pub fn particle_name_root(&self) -> &str {
        match self {
            Particle::UnknownParticle => "X",
            Particle::Gamma => "#gamma",
            Particle::Positron => "e^{#plus}",
            Particle::Electron => "e^{#minus}",
            Particle::Neutrino => "#nu",
            Particle::MuonPlus => "#mu^{#plus}",
            Particle::MuonMinus => "#mu^{#minus}",
            Particle::Pi0 => "#pi^{0}",
            Particle::PiPlus => "#pi^{#plus}",
            Particle::PiMinus => "#pi^{#minus}",
            Particle::KLong => "K^{0}_{L}",
            Particle::KPlus => "K^{#plus}",
            Particle::KMinus => "K^{#minus}",
            Particle::Neutron => "n",
            Particle::Proton => "p",
            Particle::AntiProton => "#bar{p}",
            Particle::KShort => "K^{0}_{S}",
            Particle::Eta => "#eta",
            Particle::Lambda => "#Lambda",
            Particle::SigmaPlus => "#Sigma^{#plus}",
            Particle::Sigma0 => "#Sigma^{0}",
            Particle::SigmaMinus => "#Sigma^{#minus}",
            Particle::Xi0 => "#Xi^{0}",
            Particle::XiMinus => "#Xi^{#minus}",
            Particle::OmegaMinus => "#Omega^{#minus}",
            Particle::AntiNeutron => "#bar{n}", // NOTE: #bar^{n} in particleType.h
            Particle::AntiLambda => "#bar{#Lambda}", // NOTE: #bar^{#Lambda} in particleType.h
            Particle::AntiSigmaMinus => "#bar{#Sigma}^{#minus}",
            Particle::AntiSigma0 => "#bar{#Sigma}^{0}",
            Particle::AntiSigmaPlus => "#bar{#Sigma}^{#plus}",
            Particle::AntiXi0 => "#bar{#Xi}^{0}",
            Particle::AntiXiPlus => "#bar{#Xi}^{#plus}",
            Particle::AntiOmegaPlus => "#bar{#Omega}^{#plus}",
            Particle::Deuteron => "d",
            Particle::Triton => "t",
            Particle::Helium => "He",
            Particle::Geantino => "geantino",
            Particle::He3 => "^{3}He",
            Particle::GammaOptical => "#gamma_{optical}",
            Particle::Li6 => "^{6}Li",
            Particle::Li7 => "^{7}Li",
            Particle::Be7 => "^{7}Be",
            Particle::Be9 => "^{9}Be",
            Particle::B10 => "^{10}B",
            Particle::B11 => "^{11}B",
            Particle::C12 => "^{12}C",
            Particle::N14 => "^{14}N",
            Particle::O16 => "^{16}O",
            Particle::F19 => "^{19}F",
            Particle::Ne20 => "^{20}Ne",
            Particle::Na23 => "^{23}Na",
            Particle::Mg24 => "^{23}Mg",
            Particle::Al27 => "^{27}Al",
            Particle::Si28 => "^{28}Si",
            Particle::P31 => "^{31}P",
            Particle::S32 => "^{32}S",
            Particle::Cl35 => "^{35}Cl",
            Particle::Ar36 => "^{36}Ar",
            Particle::K39 => "^{39}K",
            Particle::Ca40 => "^{40}Ca",
            Particle::Sc45 => "^{45}Sc",
            Particle::Ti48 => "^{48}Ti",
            Particle::V51 => "^{51}V",
            Particle::Cr52 => "^{52}Cr",
            Particle::Mn55 => "^{55}Mn",
            Particle::Fe56 => "^{56}Fe",
            Particle::Co59 => "^{59}Co",
            Particle::Ni58 => "^{58}Ni",
            Particle::Cu63 => "^{63}Cu",
            Particle::Zn64 => "^{64}Zn",
            Particle::Ge74 => "^{74}Ge",
            Particle::Se80 => "^{80}Se",
            Particle::Kr84 => "^{84}Kr",
            Particle::Sr88 => "^{88}Sr",
            Particle::Zr90 => "^{90}Zr",
            Particle::Mo98 => "^{98}Mo",
            Particle::Pd106 => "^{106}Pd",
            Particle::Cd114 => "^{114}Cd",
            Particle::Sn120 => "^{120}Sn",
            Particle::Xe132 => "^{132}Xe",
            Particle::Ba138 => "^{138}Ba",
            Particle::Ce140 => "^{140}Ce",
            Particle::Sm152 => "^{152}Sm",
            Particle::Dy164 => "^{164}Dy",
            Particle::Yb174 => "^{174}Yb",
            Particle::W184 => "^{184}W",
            Particle::Pt194 => "^{194}Pt",
            Particle::Au197 => "^{197}Au",
            Particle::Hg202 => "^{202}Hg",
            Particle::Pb208 => "^{208}Pb",
            Particle::U238 => "^{238}U",
            Particle::Ta181 => "^{181}Ta",
            Particle::Rho0 => "#rho^{0}",
            Particle::RhoPlus => "#rho^{#plus}",
            Particle::RhoMinus => "#rho^{#minus}",
            Particle::Omega => "#omega",
            Particle::Phi => "#phi",
            Particle::EtaPrime => "#eta'",
            Particle::A0_980 => "a_{0}(980)",
            Particle::F0_980 => "f_{0}(980)",
            Particle::KStar892Zero => "K*(892)^{0}",
            Particle::KStar892Plus => "K*(892)^{#plus}",
            Particle::KStar892Minus => "K*(892)^{#minus}",
            Particle::AntiKStar892Zero => "#bar{K*}(892)^{0}",
            Particle::K1Plus1400 => "K_{1}(1400)^{#plus}",
            Particle::K1Minus1400 => "K_{1}(1400)^{#minus}",
            Particle::B1Plus1235 => "b_{1}(1235)^{#plus}",
            Particle::Sigma1385Minus => "#Sigma(1385)^{#minus}",
            Particle::Sigma1385Zero => "#Sigma(1385)^{0}",
            Particle::Sigma1385Plus => "#Sigma(1385)^{#plus}",
            Particle::Jpsi => "J/#psi",
            Particle::EtaC => "#eta_{c}",
            Particle::ChiC0 => "#chi_{c0}",
            Particle::ChiC1 => "#chi_{c1}",
            Particle::ChiC2 => "#chi_{c2}",
            Particle::Psi2s => "#psi(2S)",
            Particle::D0 => "D^{0}",
            Particle::DPlus => "D^{#plus}", // NOTE: D{^+} in particleType.h
            Particle::DStar0 => "D^{*0}",
            Particle::DStarPlus => "D^{*#plus}", // NOTE: D^{*+} in particleType.h
            Particle::LambdaC => "#Lambda_{c}",
            Particle::AntiD0 => "#bar{D^{0}}",
            Particle::DMinus => "D^{#minus}", // NOTE: D{^-} in particleType.h
            Particle::DStarMinus => "D^{*#minus}", // NOTE: D^{*-} in particleType.h
            Particle::SigmaCPlusPlus => "#Sigma_{c}^{#plus#plus}", // NOTE: #Sigma_{c}^{++} in particleType.h
            Particle::DeltaPlusPlus => "#Delta(1232)^{#plus#plus}",
        }
    }

    pub fn particle_mass(&self) -> f64 {
        match self {
            Self::UnknownParticle => f64::MAX,
            Self::Gamma => 0.0,
            Self::Positron => 0.000510998928,
            Self::Electron => 0.000510998928,
            Self::Neutrino => 0.0,
            Self::MuonPlus => 0.1056583715,
            Self::MuonMinus => 0.1056583715,
            Self::Pi0 => 0.1349766,
            Self::PiPlus => 0.13957018,
            Self::PiMinus => 0.13957018,
            Self::KShort => 0.497614,
            Self::KLong => 0.497614,
            Self::KPlus => 0.493677,
            Self::KMinus => 0.493677,
            Self::Neutron => 0.939565379,
            Self::Proton => 0.938272046,
            Self::AntiProton => 0.938272046,
            Self::Eta => 0.547862,
            Self::Lambda => 1.115683,
            Self::SigmaPlus => 1.18937,
            Self::Sigma0 => 1.192642,
            Self::SigmaMinus => 1.197449,
            Self::Xi0 => 1.31486,
            Self::XiMinus => 1.32171,
            Self::OmegaMinus => 1.67245,
            Self::AntiNeutron => 0.939565379,
            Self::AntiLambda => 1.115683,
            Self::AntiSigmaMinus => 1.18937,
            Self::AntiSigma0 => 1.192642,
            Self::AntiSigmaPlus => 1.197449,
            Self::AntiXi0 => 1.31486,
            Self::AntiXiPlus => 1.32171,
            Self::AntiOmegaPlus => 1.67245,
            Self::Geantino => 0.0,
            Self::GammaOptical => 0.0,
            Self::Rho0 => 0.7690, // neutral only, photoproduced and other reactions. e+ e- gives 775.26
            Self::RhoPlus => 0.7665, // charged only, hadroproduced. tau decays and e+ e- gives 775.11
            Self::RhoMinus => 0.7665,
            Self::Omega => 0.78265,
            Self::EtaPrime => 0.95778,
            Self::Phi => 1.019455,
            Self::A0_980 => 0.980,
            Self::F0_980 => 0.990,
            Self::KStar892Zero => 0.89581,     // neutral only
            Self::KStar892Plus => 0.89166,     // charged only, hadroproduced
            Self::KStar892Minus => 0.89166,    // charged only, hadroproduced
            Self::AntiKStar892Zero => 0.89581, // neutral only
            Self::K1Plus1400 => 1.403,
            Self::K1Minus1400 => 1.403,
            Self::B1Plus1235 => 1.2295,
            Self::Deuteron => 1.875612859, // from NIST
            Self::Triton => 2.808921004,   // from NIST 5.00735630 x 10^-27 kg
            Self::Helium => 3.727379238,   // from NIST 6.64465675 x 10-27 kg
            Self::He3 => 2.809413498,
            Self::Li6 => 5.60305,
            Self::Li7 => 6.53536,
            Self::Be7 => 6.53622,
            Self::Be9 => 8.39479,
            Self::B10 => 9.32699,
            Self::B11 => 10.25510,
            Self::C12 => 11.17793,
            Self::N14 => 13.04378,
            Self::O16 => 14.89917,
            Self::F19 => 17.69690,
            Self::Ne20 => 18.62284,
            Self::Na23 => 21.41483,
            Self::Mg24 => 22.34193,
            Self::Al27 => 25.13314,
            Self::Si28 => 26.06034,
            Self::P31 => 28.85188,
            Self::S32 => 29.78180,
            Self::Cl35 => 32.57328,
            Self::Ar36 => 33.50356,
            Self::K39 => 36.29447,
            Self::Ca40 => 37.22492,
            Self::Sc45 => 41.87617,
            Self::Ti48 => 44.66324,
            Self::V51 => 47.45401,
            Self::Cr52 => 48.38228,
            Self::Mn55 => 51.17447,
            Self::Fe56 => 52.10307,
            Self::Co59 => 54.89593,
            Self::Ni58 => 53.96644,
            Self::Cu63 => 58.61856,
            Self::Zn64 => 59.54963,
            Self::Ge74 => 68.85715,
            Self::Se80 => 74.44178,
            Self::Kr84 => 78.16309,
            Self::Sr88 => 81.88358,
            Self::Zr90 => 83.74571,
            Self::Mo98 => 91.19832,
            Self::Pd106 => 98.64997,
            Self::Cd114 => 106.10997,
            Self::Sn120 => 111.68821,
            Self::Xe132 => 122.86796,
            Self::Ba138 => 128.45793,
            Self::Ce140 => 130.32111,
            Self::Sm152 => 141.51236,
            Self::Dy164 => 152.69909,
            Self::Yb174 => 162.02245,
            Self::Ta181 => 180.94788,
            Self::W184 => 171.34924,
            Self::Pt194 => 180.67513,
            Self::Au197 => 183.47324,
            Self::Hg202 => 188.13451,
            Self::Pb208 => 193.72899, // NIST gives 207.976627 AMU
            Self::U238 => 221.74295,
            Self::Sigma1385Minus => 1.3872,
            Self::Sigma1385Zero => 1.3837,
            Self::Sigma1385Plus => 1.38280,
            Self::DeltaPlusPlus => 1.232,
            Self::Jpsi => 3.069916,
            Self::EtaC => 2.9836,
            Self::ChiC0 => 3.41475,
            Self::ChiC1 => 3.51066,
            Self::ChiC2 => 3.55620,
            Self::Psi2s => 3.686109,
            Self::D0 => 1.86484,
            Self::AntiD0 => 1.86484,
            Self::DPlus => 1.86961,
            Self::DMinus => 1.86961,
            Self::DStar0 => 2.00685,
            Self::DStarPlus => 2.01026,
            Self::DStarMinus => 2.01026,
            Self::LambdaC => 2.28646,
            Self::SigmaCPlusPlus => 2.45397,
        }
    }

    pub fn to_geant4(&self) -> Option<String> {
        let name = match self {
            Self::UnknownParticle => "unknown",
            Self::Gamma => "gamma",
            Self::Positron => "e+",
            Self::Electron => "e-",
            Self::Neutrino => "nu_e",
            Self::MuonPlus => "mu+",
            Self::MuonMinus => "mu-",
            Self::Pi0 => "pi0",
            Self::PiPlus => "pi+",
            Self::PiMinus => "pi-",
            Self::KLong => "kaon0L",
            Self::KPlus => "kaon+",
            Self::KMinus => "kaon-",
            Self::Neutron => "neutron",
            Self::Proton => "proton",
            Self::AntiProton => "anti_proton",
            Self::KShort => "kaon0S",
            Self::Eta => "eta",
            Self::Lambda => "lambda",
            Self::SigmaPlus => "sigma+",
            Self::Sigma0 => "sigma0",
            Self::SigmaMinus => "sigma-",
            Self::Xi0 => "xi0",
            Self::XiMinus => "xi-",
            Self::OmegaMinus => "omega-",
            Self::AntiNeutron => "anti_neutron",
            Self::AntiLambda => "anti_lambda",
            Self::AntiSigmaMinus => "anti_sigma-",
            Self::AntiSigma0 => "anti_sigma0",
            Self::AntiSigmaPlus => "anti_sigma+",
            Self::AntiXi0 => "anti_xi0",
            Self::AntiXiPlus => "anti_xi+",
            Self::AntiOmegaPlus => "anti_omega+",
            Self::Deuteron => "deuteron",
            Self::Triton => "triton",
            Self::Helium => "",
            Self::Geantino => "geantino",
            Self::He3 => "He3",
            Self::GammaOptical => "opticalphoton",
            Self::Li6 => "",
            Self::Li7 => "",
            Self::Be7 => "",
            Self::Be9 => "",
            Self::B10 => "",
            Self::B11 => "",
            Self::C12 => "",
            Self::N14 => "",
            Self::O16 => "",
            Self::F19 => "",
            Self::Ne20 => "",
            Self::Na23 => "",
            Self::Mg24 => "",
            Self::Al27 => "",
            Self::Si28 => "",
            Self::P31 => "",
            Self::S32 => "",
            Self::Cl35 => "",
            Self::Ar36 => "",
            Self::K39 => "",
            Self::Ca40 => "",
            Self::Sc45 => "",
            Self::Ti48 => "",
            Self::V51 => "",
            Self::Cr52 => "",
            Self::Mn55 => "",
            Self::Fe56 => "",
            Self::Co59 => "",
            Self::Ni58 => "",
            Self::Cu63 => "",
            Self::Zn64 => "",
            Self::Ge74 => "",
            Self::Se80 => "",
            Self::Kr84 => "",
            Self::Sr88 => "",
            Self::Zr90 => "",
            Self::Mo98 => "",
            Self::Pd106 => "",
            Self::Cd114 => "",
            Self::Sn120 => "",
            Self::Xe132 => "",
            Self::Ba138 => "",
            Self::Ce140 => "",
            Self::Sm152 => "",
            Self::Dy164 => "",
            Self::Yb174 => "",
            Self::W184 => "",
            Self::Pt194 => "",
            Self::Au197 => "",
            Self::Hg202 => "",
            Self::Pb208 => "",
            Self::U238 => "",
            Self::Ta181 => "",
            Self::Rho0 => "rho0",
            Self::RhoPlus => "rho+",
            Self::RhoMinus => "rho-",
            Self::Omega => "omega",
            Self::Phi => "phi",
            Self::EtaPrime => "eta_prime",
            Self::A0_980 => "a0(980)",
            Self::F0_980 => "f0(980)",
            Self::KStar892Zero => "k_star0",
            Self::KStar892Plus => "k_star+",
            Self::KStar892Minus => "k_Star-",
            Self::AntiKStar892Zero => "anti_k_star0",
            Self::K1Plus1400 => "",
            Self::K1Minus1400 => "",
            Self::B1Plus1235 => "",
            Self::Sigma1385Minus => "",
            Self::Sigma1385Zero => "",
            Self::Sigma1385Plus => "",
            Self::Jpsi => "J/psi",
            Self::EtaC => "etac",
            Self::ChiC0 => "",
            Self::ChiC1 => "",
            Self::ChiC2 => "",
            Self::Psi2s => "",
            Self::D0 => "D0",
            Self::DPlus => "D+",
            Self::DStar0 => "",
            Self::DStarPlus => "",
            Self::LambdaC => "lambda_c+",
            Self::AntiD0 => "anti_D0",
            Self::DMinus => "D-",
            Self::DStarMinus => "",
            Self::SigmaCPlusPlus => "sigma_c++",
            Self::DeltaPlusPlus => "",
        }
        .to_string();
        if name.is_empty() { None } else { Some(name) }
    }

    pub fn from_geant4(name: &str) -> Option<Self> {
        match name {
            "unknown" => Some(Self::UnknownParticle),
            "gamma" => Some(Self::Gamma),
            "e+" => Some(Self::Positron),
            "e-" => Some(Self::Electron),
            "nu_e" => Some(Self::Neutrino),
            "mu+" => Some(Self::MuonPlus),
            "mu-" => Some(Self::MuonMinus),
            "pi0" => Some(Self::Pi0),
            "pi+" => Some(Self::PiPlus),
            "pi-" => Some(Self::PiMinus),
            "kaon0L" => Some(Self::KLong),
            "kaon+" => Some(Self::KPlus),
            "kaon-" => Some(Self::KMinus),
            "neutron" => Some(Self::Neutron),
            "proton" => Some(Self::Proton),
            "anti_proton" => Some(Self::AntiProton),
            "kaon0S" => Some(Self::KShort),
            "eta" => Some(Self::Eta),
            "lambda" => Some(Self::Lambda),
            "sigma+" => Some(Self::SigmaPlus),
            "sigma0" => Some(Self::Sigma0),
            "sigma-" => Some(Self::SigmaMinus),
            "xi0" => Some(Self::Xi0),
            "xi-" => Some(Self::XiMinus),
            "omega-" => Some(Self::OmegaMinus),
            "anti_neutron" => Some(Self::AntiNeutron),
            "anti_lambda" => Some(Self::AntiLambda),
            "anti_sigma-" => Some(Self::AntiSigmaMinus),
            "anti_sigma0" => Some(Self::AntiSigma0),
            "anti_sigma+" => Some(Self::AntiSigmaPlus),
            "anti_xi0" => Some(Self::AntiXi0),
            "anti_xi+" => Some(Self::AntiXiPlus),
            "anti_omega+" => Some(Self::AntiOmegaPlus),
            "deuteron" => Some(Self::Deuteron),
            "triton" => Some(Self::Triton),
            "geantino" => Some(Self::Geantino),
            "He3" => Some(Self::He3),
            "opticalphoton" => Some(Self::GammaOptical),
            "rho0" => Some(Self::Rho0),
            "rho+" => Some(Self::RhoPlus),
            "rho-" => Some(Self::RhoMinus),
            "omega" => Some(Self::Omega),
            "phi" => Some(Self::Phi),
            "eta_prime" => Some(Self::EtaPrime),
            "a0(980)" => Some(Self::A0_980),
            "f0(980)" => Some(Self::F0_980),
            "k_star0" => Some(Self::KStar892Zero),
            "k_star+" => Some(Self::KStar892Plus),
            "k_Star-" => Some(Self::KStar892Minus),
            "anti_k_star0" => Some(Self::AntiKStar892Zero),
            "J/psi" => Some(Self::Jpsi),
            "etac" => Some(Self::EtaC),
            "D0" => Some(Self::D0),
            "D+" => Some(Self::DPlus),
            "lambda_c+" => Some(Self::LambdaC),
            "anti_D0" => Some(Self::AntiD0),
            "D-" => Some(Self::DMinus),
            "sigma_c++" => Some(Self::SigmaCPlusPlus),
            _ => None,
        }
    }

    pub fn charge_number(&self) -> isize {
        match self {
            Self::UnknownParticle => 0,
            Self::Gamma => 0,
            Self::Positron => 1,
            Self::Electron => -1,
            Self::Neutrino => 0,
            Self::MuonPlus => 1,
            Self::MuonMinus => -1,
            Self::Pi0 => 0,
            Self::PiPlus => 1,
            Self::PiMinus => -1,
            Self::KShort => 0,
            Self::KLong => 0,
            Self::KPlus => 1,
            Self::KMinus => -1,
            Self::Neutron => 0,
            Self::Proton => 1,
            Self::AntiProton => -1,
            Self::Eta => 0,
            Self::Lambda => 0,
            Self::SigmaPlus => 1,
            Self::Sigma0 => 0,
            Self::SigmaMinus => -1,
            Self::Xi0 => 0,
            Self::XiMinus => -1,
            Self::OmegaMinus => -1,
            Self::AntiNeutron => 0,
            Self::AntiLambda => 0,
            Self::AntiSigmaMinus => -1,
            Self::AntiSigma0 => 0,
            Self::AntiSigmaPlus => 1,
            Self::AntiXi0 => 0,
            Self::AntiXiPlus => 1,
            Self::AntiOmegaPlus => 1,
            Self::Geantino => 0,
            Self::GammaOptical => 0,
            Self::Rho0 => 0,
            Self::RhoPlus => 1,
            Self::RhoMinus => -1,
            Self::Omega => 0,
            Self::EtaPrime => 0,
            Self::Phi => 0,
            Self::A0_980 => 0,
            Self::F0_980 => 0,
            Self::KStar892Zero => 0,
            Self::KStar892Plus => 1,
            Self::KStar892Minus => -1,
            Self::AntiKStar892Zero => 0,
            Self::K1Plus1400 => 1,
            Self::K1Minus1400 => -1,
            Self::B1Plus1235 => 1,
            Self::Deuteron => 1,
            Self::Triton => 1,
            Self::Helium => 2,
            Self::He3 => 2,
            Self::Li6 => 3,
            Self::Li7 => 3,
            Self::Be7 => 4,
            Self::Be9 => 4,
            Self::B10 => 5,
            Self::B11 => 5,
            Self::C12 => 6,
            Self::N14 => 7,
            Self::O16 => 8,
            Self::F19 => 9,
            Self::Ne20 => 10,
            Self::Na23 => 11,
            Self::Mg24 => 12,
            Self::Al27 => 13,
            Self::Si28 => 14,
            Self::P31 => 15,
            Self::S32 => 16,
            Self::Cl35 => 17,
            Self::Ar36 => 18,
            Self::K39 => 19,
            Self::Ca40 => 20,
            Self::Sc45 => 21,
            Self::Ti48 => 22,
            Self::V51 => 23,
            Self::Cr52 => 24,
            Self::Mn55 => 25,
            Self::Fe56 => 26,
            Self::Co59 => 27,
            Self::Ni58 => 28,
            Self::Cu63 => 29,
            Self::Zn64 => 30,
            Self::Ge74 => 32,
            Self::Se80 => 34,
            Self::Kr84 => 36,
            Self::Sr88 => 38,
            Self::Zr90 => 40,
            Self::Mo98 => 42,
            Self::Pd106 => 46,
            Self::Cd114 => 48,
            Self::Sn120 => 50,
            Self::Xe132 => 54,
            Self::Ba138 => 56,
            Self::Ce140 => 58,
            Self::Sm152 => 62,
            Self::Dy164 => 66,
            Self::Yb174 => 70,
            Self::Ta181 => 73,
            Self::W184 => 74,
            Self::Pt194 => 78,
            Self::Au197 => 79,
            Self::Hg202 => 80,
            Self::Pb208 => 82,
            Self::U238 => 92,
            Self::Sigma1385Minus => -1,
            Self::Sigma1385Zero => 0,
            Self::Sigma1385Plus => 1,
            Self::DeltaPlusPlus => 2,
            Self::Jpsi => 0,
            Self::EtaC => 0,
            Self::ChiC0 => 0,
            Self::ChiC1 => 0,
            Self::ChiC2 => 0,
            Self::Psi2s => 0,
            Self::D0 => 0,
            Self::AntiD0 => 0,
            Self::DPlus => 1,
            Self::DMinus => -1,
            Self::DStar0 => 0,
            Self::DStarPlus => 1,
            Self::DStarMinus => -1,
            Self::LambdaC => 1,
            Self::SigmaCPlusPlus => 2,
        }
    }

    pub fn to_pdg(&self) -> isize {
        match self {
            Self::UnknownParticle => 0,
            Self::Gamma => 22,
            Self::Positron => -11,
            Self::Electron => 11,
            Self::Neutrino => 121416,
            Self::MuonPlus => -13,
            Self::MuonMinus => 13,
            Self::Pi0 => 111,
            Self::PiPlus => 211,
            Self::PiMinus => -211,
            Self::KShort => 310,
            Self::KLong => 130,
            Self::KPlus => 321,
            Self::KMinus => -321,
            Self::Neutron => 2112,
            Self::Proton => 2212,
            Self::AntiProton => -2212,
            Self::Eta => 221,
            Self::Lambda => 3122,
            Self::SigmaPlus => 3222,
            Self::Sigma0 => 3212,
            Self::SigmaMinus => 3112,
            Self::Xi0 => 3322,
            Self::XiMinus => 3312,
            Self::OmegaMinus => 3334,
            Self::AntiNeutron => -2112,
            Self::AntiLambda => -3122,
            Self::AntiSigmaMinus => -3222,
            Self::AntiSigma0 => -3212,
            Self::AntiSigmaPlus => -3112,
            Self::AntiXi0 => -3322,
            Self::AntiXiPlus => -3312,
            Self::AntiOmegaPlus => -3334,
            Self::Geantino => 0,
            Self::GammaOptical => -22,
            Self::Rho0 => 113,
            Self::RhoPlus => 213,
            Self::RhoMinus => -213,
            Self::Omega => 223,
            Self::EtaPrime => 331,
            Self::Phi => 333,
            Self::A0_980 => 9000110,
            Self::F0_980 => 9010221,
            Self::KStar892Zero => 313,
            Self::AntiKStar892Zero => -313,
            Self::KStar892Plus => 323,
            Self::KStar892Minus => -323,
            Self::K1Plus1400 => 20323,
            Self::K1Minus1400 => -20323,
            Self::B1Plus1235 => 10213,
            Self::Sigma1385Minus => 3114,
            Self::Sigma1385Zero => 3214,
            Self::Sigma1385Plus => 3224,
            Self::Deuteron => 1000010020,
            Self::Triton => 1000010030,
            Self::He3 => 1000020030,
            Self::Helium => 1000020040,
            Self::Li6 => 1000030060,
            Self::Li7 => 1000030070,
            Self::Be7 => 1000040070,
            Self::Be9 => 1000040090,
            Self::B10 => 1000050100,
            Self::B11 => 1000050110,
            Self::C12 => 1000060120,
            Self::N14 => 1000070140,
            Self::O16 => 1000080160,
            Self::F19 => 1000090190,
            Self::Ne20 => 1000100200,
            Self::Na23 => 1000110230,
            Self::Mg24 => 1000120240,
            Self::Al27 => 1000130270,
            Self::Si28 => 1000140280,
            Self::P31 => 1000150310,
            Self::S32 => 1000160320,
            Self::Cl35 => 1000170350,
            Self::Ar36 => 1000180360,
            Self::K39 => 1000190390,
            Self::Ca40 => 1000200400,
            Self::Sc45 => 1000210450,
            Self::Ti48 => 1000220480,
            Self::V51 => 1000230510,
            Self::Cr52 => 1000240520,
            Self::Mn55 => 1000250550,
            Self::Fe56 => 1000260560,
            Self::Co59 => 1000270590,
            Self::Ni58 => 1000280580,
            Self::Cu63 => 1000290630,
            Self::Zn64 => 1000300640,
            Self::Ge74 => 1000320740,
            Self::Se80 => 1000340800,
            Self::Kr84 => 1000360840,
            Self::Sr88 => 1000380880,
            Self::Zr90 => 1000400900,
            Self::Mo98 => 1000420980,
            Self::Pd106 => 1000461060,
            Self::Cd114 => 1000481140,
            Self::Sn120 => 1000501200,
            Self::Xe132 => 1000541320,
            Self::Ba138 => 1000561380,
            Self::Ce140 => 1000581400,
            Self::Sm152 => 1000621520,
            Self::Dy164 => 1000661640,
            Self::Yb174 => 1000701740,
            Self::Ta181 => 1000731810,
            Self::W184 => 1000741840,
            Self::Pt194 => 1000781940,
            Self::Au197 => 1000791970,
            Self::Hg202 => 1000802020,
            Self::Pb208 => 1000822080,
            Self::U238 => 1000922380,
            Self::DeltaPlusPlus => 2224,
            Self::Jpsi => 443,
            Self::EtaC => 441,
            Self::ChiC0 => 10441,
            Self::ChiC1 => 20443,
            Self::ChiC2 => 445,
            Self::Psi2s => 100443,
            Self::D0 => 421,
            Self::AntiD0 => -421,
            Self::DPlus => 411,
            Self::DMinus => -411,
            Self::DStar0 => 423,
            Self::DStarPlus => 413,
            Self::DStarMinus => -413,
            Self::LambdaC => 4122,
            Self::SigmaCPlusPlus => 4222,
        }
    }

    pub fn from_pdg(pdgid: isize) -> Self {
        match pdgid {
            0 => Self::UnknownParticle,
            22 => Self::Gamma,
            -11 => Self::Positron,
            11 => Self::Electron,
            121416 => Self::Neutrino,
            -13 => Self::MuonPlus,
            13 => Self::MuonMinus,
            111 => Self::Pi0,
            211 => Self::PiPlus,
            -211 => Self::PiMinus,
            310 => Self::KShort,
            130 => Self::KLong,
            321 => Self::KPlus,
            -321 => Self::KMinus,
            2112 => Self::Neutron,
            2212 => Self::Proton,
            -2212 => Self::AntiProton,
            221 => Self::Eta,
            3122 => Self::Lambda,
            3222 => Self::SigmaPlus,
            3212 => Self::Sigma0,
            3112 => Self::SigmaMinus,
            3322 => Self::Xi0,
            3312 => Self::XiMinus,
            3334 => Self::OmegaMinus,
            -2112 => Self::AntiNeutron,
            -3122 => Self::AntiLambda,
            -3222 => Self::AntiSigmaMinus,
            -3212 => Self::AntiSigma0,
            -3112 => Self::AntiSigmaPlus,
            -3322 => Self::AntiXi0,
            -3312 => Self::AntiXiPlus,
            -3334 => Self::AntiOmegaPlus,
            113 => Self::Rho0,
            213 => Self::RhoPlus,
            -213 => Self::RhoMinus,
            223 => Self::Omega,
            331 => Self::EtaPrime,
            333 => Self::Phi,
            9000110 => Self::A0_980,
            9010221 => Self::F0_980,
            313 => Self::KStar892Zero,
            -313 => Self::AntiKStar892Zero,
            323 => Self::KStar892Plus,
            -323 => Self::KStar892Minus,
            20323 => Self::K1Plus1400,
            -20323 => Self::K1Minus1400,
            10213 => Self::B1Plus1235,
            3114 => Self::Sigma1385Minus,
            3214 => Self::Sigma1385Zero,
            3224 => Self::Sigma1385Plus,
            1000010020 => Self::Deuteron,
            1000010030 => Self::Triton,
            1000020030 => Self::He3,
            1000020040 => Self::Helium,
            1000030060 => Self::Li6,
            1000030070 => Self::Li7,
            1000040070 => Self::Be7,
            1000040090 => Self::Be9,
            1000050100 => Self::B10,
            1000050110 => Self::B11,
            1000060120 => Self::C12,
            1000070140 => Self::N14,
            1000080160 => Self::O16,
            1000090190 => Self::F19,
            1000100200 => Self::Ne20,
            1000110230 => Self::Na23,
            1000120240 => Self::Mg24,
            1000130270 => Self::Al27,
            1000140280 => Self::Si28,
            1000150310 => Self::P31,
            1000160320 => Self::S32,
            1000170350 => Self::Cl35,
            1000180360 => Self::Ar36,
            1000190390 => Self::K39,
            1000200400 => Self::Ca40,
            1000210450 => Self::Sc45,
            1000220480 => Self::Ti48,
            1000230510 => Self::V51,
            1000240520 => Self::Cr52,
            1000250550 => Self::Mn55,
            1000260560 => Self::Fe56,
            1000270590 => Self::Co59,
            1000280580 => Self::Ni58,
            1000290630 => Self::Cu63,
            1000300640 => Self::Zn64,
            1000320740 => Self::Ge74,
            1000340800 => Self::Se80,
            1000360840 => Self::Kr84,
            1000380880 => Self::Sr88,
            1000400900 => Self::Zr90,
            1000420980 => Self::Mo98,
            1000461060 => Self::Pd106,
            1000481140 => Self::Cd114,
            1000501200 => Self::Sn120,
            1000541320 => Self::Xe132,
            1000561380 => Self::Ba138,
            1000581400 => Self::Ce140,
            1000621520 => Self::Sm152,
            1000661640 => Self::Dy164,
            1000701740 => Self::Yb174,
            1000731810 => Self::Ta181,
            1000741840 => Self::W184,
            1000781940 => Self::Pt194,
            1000791970 => Self::Au197,
            1000802020 => Self::Hg202,
            1000822080 => Self::Pb208,
            1000922380 => Self::U238,
            2224 => Self::DeltaPlusPlus,
            443 => Self::Jpsi,
            441 => Self::EtaC,
            10441 => Self::ChiC0,
            20443 => Self::ChiC1,
            445 => Self::ChiC2,
            100443 => Self::Psi2s,
            421 => Self::D0,
            -421 => Self::AntiD0,
            411 => Self::DPlus,
            -411 => Self::DMinus,
            423 => Self::DStar0,
            413 => Self::DStarPlus,
            -413 => Self::DStarMinus,
            4122 => Self::LambdaC,
            4222 => Self::SigmaCPlusPlus,
            _ => Self::UnknownParticle,
        }
    }

    pub fn is_decaying(&self) -> bool {
        matches!(
            self,
            Self::UnknownParticle
                | Self::Pi0
                | Self::KShort
                | Self::Eta
                | Self::Lambda
                | Self::SigmaPlus
                | Self::Sigma0
                | Self::SigmaMinus
                | Self::Xi0
                | Self::XiMinus
                | Self::OmegaMinus
                | Self::AntiLambda
                | Self::AntiSigmaMinus
                | Self::AntiSigma0
                | Self::AntiSigmaPlus
                | Self::AntiXi0
                | Self::AntiXiPlus
                | Self::AntiOmegaPlus
                | Self::Geantino
                | Self::GammaOptical
                | Self::Rho0
                | Self::RhoPlus
                | Self::RhoMinus
                | Self::Omega
                | Self::Phi
                | Self::EtaPrime
                | Self::A0_980
                | Self::F0_980
                | Self::KStar892Zero
                | Self::KStar892Plus
                | Self::KStar892Minus
                | Self::AntiKStar892Zero
                | Self::K1Plus1400
                | Self::K1Minus1400
                | Self::B1Plus1235
                | Self::Sigma1385Minus
                | Self::Sigma1385Zero
                | Self::Sigma1385Plus
                | Self::Jpsi
                | Self::EtaC
                | Self::ChiC0
                | Self::ChiC1
                | Self::ChiC2
                | Self::Psi2s
                | Self::D0
                | Self::DPlus
                | Self::DStar0
                | Self::DStarPlus
                | Self::LambdaC
                | Self::AntiD0
                | Self::DMinus
                | Self::DStarMinus
                | Self::SigmaCPlusPlus
                | Self::DeltaPlusPlus
        )
    }

    pub fn is_final_state(&self) -> bool {
        !self.is_decaying()
    }

    pub fn to_multiplex_power(&self) -> Option<usize> {
        match self {
            // Final-state particles (and pi0) (decimal: 10^power):
            Self::Gamma => Some(0),
            Self::Positron => Some(1),
            Self::Electron => Some(2),
            Self::Neutrino => Some(3),
            Self::MuonPlus => Some(4),
            Self::MuonMinus => Some(5),
            Self::Pi0 => Some(6),
            Self::PiPlus => Some(7),
            Self::PiMinus => Some(8),
            Self::KLong => Some(9),
            Self::KPlus => Some(10),
            Self::KMinus => Some(11),
            Self::Neutron => Some(12),
            Self::Proton => Some(13),
            Self::AntiProton => Some(14),
            Self::AntiNeutron => Some(15),

            // Decaying particles (without pi0): (binary: 2^power)
            Self::KShort => Some(0),
            Self::Eta => Some(1),
            Self::Lambda => Some(2),
            Self::SigmaPlus => Some(3),
            Self::Sigma0 => Some(4),
            Self::SigmaMinus => Some(5),
            Self::Xi0 => Some(6),
            Self::XiMinus => Some(7),
            Self::OmegaMinus => Some(8),
            Self::AntiLambda => Some(9),
            Self::AntiSigmaMinus => Some(10),
            Self::AntiSigma0 => Some(11),
            Self::AntiSigmaPlus => Some(12),
            Self::AntiXi0 => Some(13),
            Self::AntiXiPlus => Some(14),
            Self::AntiOmegaPlus => Some(15),
            Self::Deuteron => Some(16),
            Self::Rho0 => Some(17),
            Self::RhoPlus => Some(18),
            Self::RhoMinus => Some(19),
            Self::Omega => Some(20),
            Self::EtaPrime => Some(21),
            Self::Phi => Some(22),
            Self::A0_980 => Some(23),
            Self::F0_980 => Some(24),
            Self::KStar892Zero => Some(25),
            Self::KStar892Plus => Some(26),
            Self::KStar892Minus => Some(27),
            Self::AntiKStar892Zero => Some(28),
            Self::K1Plus1400 => Some(29),
            Self::K1Minus1400 => Some(30),
            Self::B1Plus1235 => Some(31),
            Self::Sigma1385Minus => Some(32),
            Self::Sigma1385Zero => Some(33),
            Self::Sigma1385Plus => Some(34),
            Self::DeltaPlusPlus => Some(35),
            Self::Jpsi => Some(36),
            Self::EtaC => Some(37),
            Self::ChiC0 => Some(38),
            Self::ChiC1 => Some(39),
            Self::ChiC2 => Some(40),
            Self::Psi2s => Some(41),
            Self::D0 => Some(42),
            Self::DPlus => Some(43),
            Self::DStar0 => Some(44),
            Self::DStarPlus => Some(45),
            Self::LambdaC => Some(46),
            Self::AntiD0 => Some(47),
            Self::DMinus => Some(48),
            Self::DStarMinus => Some(49),
            Self::SigmaCPlusPlus => Some(50),
            _ => None,
        }
    }

    pub fn from_multiplex_power(bit: usize, decaying: bool) -> Self {
        if !decaying {
            match bit {
                0 => Self::Gamma,
                1 => Self::Positron,
                2 => Self::Electron,
                3 => Self::Neutrino,
                4 => Self::MuonPlus,
                5 => Self::MuonMinus,
                6 => Self::Pi0,
                7 => Self::PiPlus,
                8 => Self::PiMinus,
                9 => Self::KLong,
                10 => Self::KPlus,
                11 => Self::KMinus,
                12 => Self::Neutron,
                13 => Self::Proton,
                14 => Self::AntiProton,
                15 => Self::AntiNeutron,
                _ => Self::UnknownParticle,
            }
        } else {
            match bit {
                0 => Self::KShort,
                1 => Self::Eta,
                2 => Self::Lambda,
                3 => Self::SigmaPlus,
                4 => Self::Sigma0,
                5 => Self::SigmaMinus,
                6 => Self::Xi0,
                7 => Self::XiMinus,
                8 => Self::OmegaMinus,
                9 => Self::AntiLambda,
                10 => Self::AntiSigmaMinus,
                11 => Self::AntiSigma0,
                12 => Self::AntiSigmaPlus,
                13 => Self::AntiXi0,
                14 => Self::AntiXiPlus,
                15 => Self::AntiOmegaPlus,
                16 => Self::Deuteron,
                17 => Self::Rho0,
                18 => Self::RhoPlus,
                19 => Self::RhoMinus,
                20 => Self::Omega,
                21 => Self::EtaPrime,
                22 => Self::Phi,
                23 => Self::A0_980,
                24 => Self::F0_980,
                25 => Self::KStar892Zero,
                26 => Self::KStar892Plus,
                27 => Self::KStar892Minus,
                28 => Self::AntiKStar892Zero,
                29 => Self::K1Plus1400,
                30 => Self::K1Minus1400,
                31 => Self::B1Plus1235,
                32 => Self::Sigma1385Minus,
                33 => Self::Sigma1385Zero,
                34 => Self::Sigma1385Plus,
                35 => Self::DeltaPlusPlus,
                36 => Self::Jpsi,
                37 => Self::EtaC,
                38 => Self::ChiC0,
                39 => Self::ChiC1,
                40 => Self::ChiC2,
                41 => Self::Psi2s,
                42 => Self::D0,
                43 => Self::DPlus,
                44 => Self::DStar0,
                45 => Self::DStarPlus,
                46 => Self::LambdaC,
                47 => Self::AntiD0,
                48 => Self::DMinus,
                49 => Self::DStarMinus,
                50 => Self::SigmaCPlusPlus,
                _ => Self::UnknownParticle,
            }
        }
    }

    pub fn charge(&self) -> Charge {
        if self.is_unknown() {
            return Charge::AllCharges;
        }
        let charge_value = self.charge_number();
        if charge_value == 0 {
            Charge::Neutral
        } else if charge_value > 0 {
            Charge::Positive
        } else if charge_value < 0 {
            Charge::Negative
        } else {
            Charge::AllCharges
        }
    }

    /// Deduce a reconstructed track's particle type from charge and mass.
    pub fn from_charge_and_mass(charge: f64, mass: f64) -> Particle {
        let m_tol = 0.010;
        if charge > 0.1 {
            if (mass - Self::Triton.particle_mass()).abs() < m_tol {
                return Self::Triton;
            }

            if (mass - Self::Deuteron.particle_mass()).abs() < m_tol {
                return Self::Deuteron;
            }
            if (mass - Self::Proton.particle_mass()).abs() < m_tol {
                return Self::Proton;
            }
            if (mass - Self::PiPlus.particle_mass()).abs() < m_tol {
                return Self::PiPlus;
            }
            if (mass - Self::KPlus.particle_mass()).abs() < m_tol {
                return Self::KPlus;
            }
            if (mass - Self::Positron.particle_mass()).abs() < m_tol {
                return Self::Positron;
            }
            if (mass - Self::MuonPlus.particle_mass()).abs() < m_tol {
                return Self::MuonPlus;
            }
        } else if charge < -0.1 {
            if (mass - Self::PiMinus.particle_mass()).abs() < m_tol {
                return Self::PiMinus;
            }
            if (mass - Self::KMinus.particle_mass()).abs() < m_tol {
                return Self::KMinus;
            }
            if (mass - Self::MuonMinus.particle_mass()).abs() < m_tol {
                return Self::MuonMinus;
            }
            if (mass - Self::Electron.particle_mass()).abs() < m_tol {
                return Self::Electron;
            }
            if (mass - Self::AntiProton.particle_mass()).abs() < m_tol {
                return Self::AntiProton;
            }
        } else {
            if (mass - Self::Gamma.particle_mass()).abs() < m_tol {
                return Self::Gamma;
            }
            if (mass - Self::Neutron.particle_mass()).abs() < m_tol {
                return Self::Neutron;
            }
        }
        Self::UnknownParticle
    }
}

impl fmt::Display for Particle {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.enum_name())
    }
}

impl FromStr for Particle {
    type Err = crate::GlueXCoreError;

    fn from_str(name: &str) -> Result<Self, Self::Err> {
        Self::VARIANTS
            .iter()
            .copied()
            .find(|particle| particle.enum_name() == name)
            .ok_or_else(|| crate::GlueXCoreError::ParticleParse(name.to_owned()))
    }
}

impl From<Particle> for hddm::Particle {
    fn from(value: Particle) -> Self {
        match value {
            Particle::UnknownParticle => hddm::Particle::UnknownParticle,
            Particle::Gamma => hddm::Particle::Gamma,
            Particle::Positron => hddm::Particle::Positron,
            Particle::Electron => hddm::Particle::Electron,
            Particle::Neutrino => hddm::Particle::Neutrino,
            Particle::MuonPlus => hddm::Particle::MuonPlus,
            Particle::MuonMinus => hddm::Particle::MuonMinus,
            Particle::Pi0 => hddm::Particle::Pi0,
            Particle::PiPlus => hddm::Particle::PiPlus,
            Particle::PiMinus => hddm::Particle::PiMinus,
            Particle::KLong => hddm::Particle::KLong,
            Particle::KPlus => hddm::Particle::KPlus,
            Particle::KMinus => hddm::Particle::KMinus,
            Particle::Neutron => hddm::Particle::Neutron,
            Particle::Proton => hddm::Particle::Proton,
            Particle::AntiProton => hddm::Particle::AntiProton,
            Particle::KShort => hddm::Particle::KShort,
            Particle::Eta => hddm::Particle::Eta,
            Particle::Lambda => hddm::Particle::Lambda,
            Particle::SigmaPlus => hddm::Particle::SigmaPlus,
            Particle::Sigma0 => hddm::Particle::Sigma0,
            Particle::SigmaMinus => hddm::Particle::SigmaMinus,
            Particle::Xi0 => hddm::Particle::Xi0,
            Particle::XiMinus => hddm::Particle::XiMinus,
            Particle::OmegaMinus => hddm::Particle::OmegaMinus,
            Particle::AntiNeutron => hddm::Particle::AntiNeutron,
            Particle::AntiLambda => hddm::Particle::AntiLambda,
            Particle::AntiSigmaMinus => hddm::Particle::AntiSigmaMinus,
            Particle::AntiSigma0 => hddm::Particle::AntiSigma0,
            Particle::AntiSigmaPlus => hddm::Particle::AntiSigmaPlus,
            Particle::AntiXi0 => hddm::Particle::AntiXi0,
            Particle::AntiXiPlus => hddm::Particle::AntiXiPlus,
            Particle::AntiOmegaPlus => hddm::Particle::AntiOmegaPlus,
            Particle::Deuteron => hddm::Particle::Deuteron,
            Particle::Triton => hddm::Particle::Triton,
            Particle::Helium => hddm::Particle::Helium,
            Particle::Geantino => hddm::Particle::Geantino,
            Particle::He3 => hddm::Particle::He3,
            Particle::GammaOptical => hddm::Particle::GammaOptical,
            Particle::Li6 => hddm::Particle::Li6,
            Particle::Li7 => hddm::Particle::Li7,
            Particle::Be7 => hddm::Particle::Be7,
            Particle::Be9 => hddm::Particle::Be9,
            Particle::B10 => hddm::Particle::B10,
            Particle::B11 => hddm::Particle::B11,
            Particle::C12 => hddm::Particle::C12,
            Particle::N14 => hddm::Particle::N14,
            Particle::O16 => hddm::Particle::O16,
            Particle::F19 => hddm::Particle::F19,
            Particle::Ne20 => hddm::Particle::Ne20,
            Particle::Na23 => hddm::Particle::Na23,
            Particle::Mg24 => hddm::Particle::Mg24,
            Particle::Al27 => hddm::Particle::Al27,
            Particle::Si28 => hddm::Particle::Si28,
            Particle::P31 => hddm::Particle::P31,
            Particle::S32 => hddm::Particle::S32,
            Particle::Cl35 => hddm::Particle::Cl35,
            Particle::Ar36 => hddm::Particle::Ar36,
            Particle::K39 => hddm::Particle::K39,
            Particle::Ca40 => hddm::Particle::Ca40,
            Particle::Sc45 => hddm::Particle::Sc45,
            Particle::Ti48 => hddm::Particle::Ti48,
            Particle::V51 => hddm::Particle::V51,
            Particle::Cr52 => hddm::Particle::Cr52,
            Particle::Mn55 => hddm::Particle::Mn55,
            Particle::Fe56 => hddm::Particle::Fe56,
            Particle::Co59 => hddm::Particle::Co59,
            Particle::Ni58 => hddm::Particle::Ni58,
            Particle::Cu63 => hddm::Particle::Cu63,
            Particle::Zn64 => hddm::Particle::Zn64,
            Particle::Ge74 => hddm::Particle::Ge74,
            Particle::Se80 => hddm::Particle::Se80,
            Particle::Kr84 => hddm::Particle::Kr84,
            Particle::Sr88 => hddm::Particle::Sr88,
            Particle::Zr90 => hddm::Particle::Zr90,
            Particle::Mo98 => hddm::Particle::Mo98,
            Particle::Pd106 => hddm::Particle::Pd106,
            Particle::Cd114 => hddm::Particle::Cd114,
            Particle::Sn120 => hddm::Particle::Sn120,
            Particle::Xe132 => hddm::Particle::Xe132,
            Particle::Ba138 => hddm::Particle::Ba138,
            Particle::Ce140 => hddm::Particle::Ce140,
            Particle::Sm152 => hddm::Particle::Sm152,
            Particle::Dy164 => hddm::Particle::Dy164,
            Particle::Yb174 => hddm::Particle::Yb174,
            Particle::W184 => hddm::Particle::W184,
            Particle::Pt194 => hddm::Particle::Pt194,
            Particle::Au197 => hddm::Particle::Au197,
            Particle::Hg202 => hddm::Particle::Hg202,
            Particle::Pb208 => hddm::Particle::Pb208,
            Particle::U238 => hddm::Particle::U238,
            Particle::Ta181 => hddm::Particle::Ta181,
            Particle::Rho0 => hddm::Particle::Rho0,
            Particle::RhoPlus => hddm::Particle::RhoPlus,
            Particle::RhoMinus => hddm::Particle::RhoMinus,
            Particle::Omega => hddm::Particle::omega,
            Particle::Phi => hddm::Particle::phiMeson,
            Particle::EtaPrime => hddm::Particle::EtaPrime,
            Particle::A0_980 => hddm::Particle::a0_980,
            Particle::F0_980 => hddm::Particle::f0_980,
            Particle::KStar892Zero => hddm::Particle::KStar_892_0,
            Particle::KStar892Plus => hddm::Particle::KStar_892_Plus,
            Particle::KStar892Minus => hddm::Particle::KStar_892_Minus,
            Particle::AntiKStar892Zero => hddm::Particle::AntiKStar_892_0,
            Particle::K1Plus1400 => hddm::Particle::K1_1400_Plus,
            Particle::K1Minus1400 => hddm::Particle::K1_1400_Minus,
            Particle::B1Plus1235 => hddm::Particle::b1_1235_Plus,
            Particle::Sigma1385Minus => hddm::Particle::Sigma_1385_Minus,
            Particle::Sigma1385Zero => hddm::Particle::Sigma_1385_0,
            Particle::Sigma1385Plus => hddm::Particle::Sigma_1385_Plus,
            Particle::Jpsi => hddm::Particle::Jpsi,
            Particle::EtaC => hddm::Particle::Eta_c,
            Particle::ChiC0 => hddm::Particle::Chi_c0,
            Particle::ChiC1 => hddm::Particle::Chi_c1,
            Particle::ChiC2 => hddm::Particle::Chi_c2,
            Particle::Psi2s => hddm::Particle::Psi2s,
            Particle::D0 => hddm::Particle::D0,
            Particle::DPlus => hddm::Particle::DPlus,
            Particle::DStar0 => hddm::Particle::Dstar0,
            Particle::DStarPlus => hddm::Particle::DstarPlus,
            Particle::LambdaC => hddm::Particle::Lambda_c,
            Particle::AntiD0 => hddm::Particle::AntiD0,
            Particle::DMinus => hddm::Particle::DMinus,
            Particle::DStarMinus => hddm::Particle::DstarMinus,
            Particle::SigmaCPlusPlus => hddm::Particle::Sigma_cPlusPlus,
            Particle::DeltaPlusPlus => hddm::Particle::DeltaPlusPlus,
        }
    }
}

impl From<&Particle> for hddm::Particle {
    fn from(value: &Particle) -> Self {
        (*value).into()
    }
}

impl From<hddm::Particle> for Particle {
    fn from(value: hddm::Particle) -> Self {
        match value {
            hddm::Particle::UnknownParticle => Particle::UnknownParticle,
            hddm::Particle::Gamma => Particle::Gamma,
            hddm::Particle::Positron => Particle::Positron,
            hddm::Particle::Electron => Particle::Electron,
            hddm::Particle::Neutrino => Particle::Neutrino,
            hddm::Particle::MuonPlus => Particle::MuonPlus,
            hddm::Particle::MuonMinus => Particle::MuonMinus,
            hddm::Particle::Pi0 => Particle::Pi0,
            hddm::Particle::PiPlus => Particle::PiPlus,
            hddm::Particle::PiMinus => Particle::PiMinus,
            hddm::Particle::KLong => Particle::KLong,
            hddm::Particle::KPlus => Particle::KPlus,
            hddm::Particle::KMinus => Particle::KMinus,
            hddm::Particle::Neutron => Particle::Neutron,
            hddm::Particle::Proton => Particle::Proton,
            hddm::Particle::AntiProton => Particle::AntiProton,
            hddm::Particle::KShort => Particle::KShort,
            hddm::Particle::Eta => Particle::Eta,
            hddm::Particle::Lambda => Particle::Lambda,
            hddm::Particle::SigmaPlus => Particle::SigmaPlus,
            hddm::Particle::Sigma0 => Particle::Sigma0,
            hddm::Particle::SigmaMinus => Particle::SigmaMinus,
            hddm::Particle::Xi0 => Particle::Xi0,
            hddm::Particle::XiMinus => Particle::XiMinus,
            hddm::Particle::OmegaMinus => Particle::OmegaMinus,
            hddm::Particle::AntiNeutron => Particle::AntiNeutron,
            hddm::Particle::AntiLambda => Particle::AntiLambda,
            hddm::Particle::AntiSigmaMinus => Particle::AntiSigmaMinus,
            hddm::Particle::AntiSigma0 => Particle::AntiSigma0,
            hddm::Particle::AntiSigmaPlus => Particle::AntiSigmaPlus,
            hddm::Particle::AntiXi0 => Particle::AntiXi0,
            hddm::Particle::AntiXiPlus => Particle::AntiXiPlus,
            hddm::Particle::AntiOmegaPlus => Particle::AntiOmegaPlus,
            hddm::Particle::Deuteron => Particle::Deuteron,
            hddm::Particle::Triton => Particle::Triton,
            hddm::Particle::Helium => Particle::Helium,
            hddm::Particle::Geantino => Particle::Geantino,
            hddm::Particle::He3 => Particle::He3,
            hddm::Particle::GammaOptical => Particle::GammaOptical,
            hddm::Particle::Li6 => Particle::Li6,
            hddm::Particle::Li7 => Particle::Li7,
            hddm::Particle::Be7 => Particle::Be7,
            hddm::Particle::Be9 => Particle::Be9,
            hddm::Particle::B10 => Particle::B10,
            hddm::Particle::B11 => Particle::B11,
            hddm::Particle::C12 => Particle::C12,
            hddm::Particle::N14 => Particle::N14,
            hddm::Particle::O16 => Particle::O16,
            hddm::Particle::F19 => Particle::F19,
            hddm::Particle::Ne20 => Particle::Ne20,
            hddm::Particle::Na23 => Particle::Na23,
            hddm::Particle::Mg24 => Particle::Mg24,
            hddm::Particle::Al27 => Particle::Al27,
            hddm::Particle::Si28 => Particle::Si28,
            hddm::Particle::P31 => Particle::P31,
            hddm::Particle::S32 => Particle::S32,
            hddm::Particle::Cl35 => Particle::Cl35,
            hddm::Particle::Ar36 => Particle::Ar36,
            hddm::Particle::K39 => Particle::K39,
            hddm::Particle::Ca40 => Particle::Ca40,
            hddm::Particle::Sc45 => Particle::Sc45,
            hddm::Particle::Ti48 => Particle::Ti48,
            hddm::Particle::V51 => Particle::V51,
            hddm::Particle::Cr52 => Particle::Cr52,
            hddm::Particle::Mn55 => Particle::Mn55,
            hddm::Particle::Fe56 => Particle::Fe56,
            hddm::Particle::Co59 => Particle::Co59,
            hddm::Particle::Ni58 => Particle::Ni58,
            hddm::Particle::Cu63 => Particle::Cu63,
            hddm::Particle::Zn64 => Particle::Zn64,
            hddm::Particle::Ge74 => Particle::Ge74,
            hddm::Particle::Se80 => Particle::Se80,
            hddm::Particle::Kr84 => Particle::Kr84,
            hddm::Particle::Sr88 => Particle::Sr88,
            hddm::Particle::Zr90 => Particle::Zr90,
            hddm::Particle::Mo98 => Particle::Mo98,
            hddm::Particle::Pd106 => Particle::Pd106,
            hddm::Particle::Cd114 => Particle::Cd114,
            hddm::Particle::Sn120 => Particle::Sn120,
            hddm::Particle::Xe132 => Particle::Xe132,
            hddm::Particle::Ba138 => Particle::Ba138,
            hddm::Particle::Ce140 => Particle::Ce140,
            hddm::Particle::Sm152 => Particle::Sm152,
            hddm::Particle::Dy164 => Particle::Dy164,
            hddm::Particle::Yb174 => Particle::Yb174,
            hddm::Particle::W184 => Particle::W184,
            hddm::Particle::Pt194 => Particle::Pt194,
            hddm::Particle::Au197 => Particle::Au197,
            hddm::Particle::Hg202 => Particle::Hg202,
            hddm::Particle::Pb208 => Particle::Pb208,
            hddm::Particle::U238 => Particle::U238,
            hddm::Particle::Ta181 => Particle::Ta181,
            hddm::Particle::Rho0 => Particle::Rho0,
            hddm::Particle::RhoPlus => Particle::RhoPlus,
            hddm::Particle::RhoMinus => Particle::RhoMinus,
            hddm::Particle::omega => Particle::Omega,
            hddm::Particle::phiMeson => Particle::Phi,
            hddm::Particle::EtaPrime => Particle::EtaPrime,
            hddm::Particle::a0_980 => Particle::A0_980,
            hddm::Particle::f0_980 => Particle::F0_980,
            hddm::Particle::KStar_892_0 => Particle::KStar892Zero,
            hddm::Particle::KStar_892_Plus => Particle::KStar892Plus,
            hddm::Particle::KStar_892_Minus => Particle::KStar892Minus,
            hddm::Particle::AntiKStar_892_0 => Particle::AntiKStar892Zero,
            hddm::Particle::K1_1400_Plus => Particle::K1Plus1400,
            hddm::Particle::K1_1400_Minus => Particle::K1Minus1400,
            hddm::Particle::b1_1235_Plus => Particle::B1Plus1235,
            hddm::Particle::Sigma_1385_Minus => Particle::Sigma1385Minus,
            hddm::Particle::Sigma_1385_0 => Particle::Sigma1385Zero,
            hddm::Particle::Sigma_1385_Plus => Particle::Sigma1385Plus,
            hddm::Particle::Jpsi => Particle::Jpsi,
            hddm::Particle::Eta_c => Particle::EtaC,
            hddm::Particle::Chi_c0 => Particle::ChiC0,
            hddm::Particle::Chi_c1 => Particle::ChiC1,
            hddm::Particle::Chi_c2 => Particle::ChiC2,
            hddm::Particle::Psi2s => Particle::Psi2s,
            hddm::Particle::D0 => Particle::D0,
            hddm::Particle::DPlus => Particle::DPlus,
            hddm::Particle::Dstar0 => Particle::DStar0,
            hddm::Particle::DstarPlus => Particle::DStarPlus,
            hddm::Particle::Lambda_c => Particle::LambdaC,
            hddm::Particle::AntiD0 => Particle::AntiD0,
            hddm::Particle::DMinus => Particle::DMinus,
            hddm::Particle::DstarMinus => Particle::DStarMinus,
            hddm::Particle::Sigma_cPlusPlus => Particle::SigmaCPlusPlus,
            hddm::Particle::DeltaPlusPlus => Particle::DeltaPlusPlus,
        }
    }
}

impl From<&hddm::Particle> for Particle {
    fn from(value: &hddm::Particle) -> Self {
        (*value).into()
    }
}

#[cfg(test)]
mod tests {
    use super::{Charge, Particle};

    #[test]
    fn idiomatic_particle_names_preserve_external_conversions() {
        assert_eq!(Particle::Omega, Particle::from_particle_type("Omega"));
        assert_eq!(Particle::Phi, Particle::from_pdg(333));
        assert_eq!(Particle::KStar892Zero.to_string(), "KStar_892_0");
        assert_eq!(Particle::EtaC.to_string(), "Eta_c");
        assert_eq!(
            "KStar_892_0".parse::<Particle>().unwrap(),
            Particle::KStar892Zero
        );
        assert_eq!(
            hddm::Particle::from(Particle::SigmaCPlusPlus),
            hddm::Particle::Sigma_cPlusPlus
        );
    }

    #[test]
    fn particle_type_labels_round_trip_separately_from_enum_names() {
        assert_eq!(
            Particle::from_particle_type(Particle::K1Plus1400.to_particle_type()),
            Particle::K1Plus1400
        );
        assert_eq!(
            Particle::from_particle_type(Particle::C12.to_particle_type()),
            Particle::C12
        );
    }

    #[test]
    fn named_particle_conversions_preserve_external_values() {
        assert_eq!(Particle::Phi.to_evtgen(), "phi");
        assert_eq!(Particle::Phi.to_geant4().as_deref(), Some("phi"));
        assert_eq!(Particle::from_geant4("phi"), Some(Particle::Phi));
        assert!(Particle::Phi.is_decaying());
        assert!(Particle::Proton.is_final_state());
        assert_eq!(Particle::SigmaCPlusPlus.to_multiplex_power(), Some(50));
        assert_eq!(
            Particle::from_multiplex_power(50, true),
            Particle::SigmaCPlusPlus
        );
        assert_eq!(Particle::Proton.charge(), Charge::Positive);
        assert_eq!(
            Particle::from_charge_and_mass(1.0, Particle::Proton.particle_mass()),
            Particle::Proton
        );
    }
}
